name: Linting
on: [pull_request]

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: |
          uv sync --all-extras
      - name: Run linters
        run: |
          uv run black --check .
          uv run isort --check .
